# Generated by Django 4.1.7 on 2023-03-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='Post', on_delete=django.db.models.deletion.CASCADE, to='instagram.post', verbose_name='Публикация'),
        ),
    ]
