# Generated by Django 4.1.7 on 2023-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='post',
            name='lakes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
