# Generated by Django 4.1.7 on 2023-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_post_comments_count_post_lakes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts', verbose_name='Картина'),
        ),
    ]
