# Generated by Django 4.1.7 on 2023-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lakes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='laked_post',
            field=models.ManyToManyField(related_name='user_likes', to='instagram.post', verbose_name='Лайки поста'),
        ),
    ]
