# Generated by Django 4.1.7 on 2023-03-24 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0008_remove_post_lakes_count_post_laked_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='laked_post',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки поста'),
        ),
    ]
