# Generated by Django 4.1.7 on 2023-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_post_commented_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commented_post',
        ),
    ]
