# Generated by Django 4.1.7 on 2023-03-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_post_commented_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commented_post',
        ),
    ]
