# Generated by Django 4.1.7 on 2023-03-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='laked_post',
        ),
    ]
