# Generated by Django 4.1.7 on 2023-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
