# Generated by Django 4.1.7 on 2023-03-24 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='info',
            field=models.CharField(blank=True, default='Info', max_length=200, null=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default=-1339, max_length=80, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscribers_count',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions_count',
            field=models.IntegerField(default=0, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscriptions_acc', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
