# Generated by Django 4.1.7 on 2023-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_post_image'),
        ('accounts', '0004_account_info_account_phone_account_subscribers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='commented_post',
            field=models.ManyToManyField(related_name='user_comments', to='instagram.comment', verbose_name='Прокамментированные посты'),
        ),
    ]
