# Generated by Django 4.1.7 on 2023-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_commented_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='laked_post',
        ),
    ]
