# Generated by Django 4.1.7 on 2023-03-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_laked_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='commented_post',
        ),
    ]
