# Generated by Django 4.1.7 on 2023-03-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_subscribers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='commented_post',
        ),
    ]
