# Generated by Django 4.1.7 on 2023-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_commented_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribers_count',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions_count',
            field=models.IntegerField(default=0, verbose_name='Подписки'),
        ),
    ]
