# Generated by Django 4.1.7 on 2023-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_remove_post_commented_post'),
        ('accounts', '0010_account_subscribers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='commented_post',
            field=models.ManyToManyField(related_name='user_comments', to='instagram.post', verbose_name='Прокамментированные посты'),
        ),
    ]
