# Generated by Django 4.1.7 on 2023-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscriptions_count',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='8-777-222-22-22', max_length=80, null=True, verbose_name='Телефон'),
        ),
    ]
