# Generated by Django 4.1.7 on 2023-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_remove_post_laked_post'),
        ('accounts', '0014_remove_account_subscribers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='laked_post',
            field=models.ManyToManyField(related_name='user_likes', to='instagram.post', verbose_name='Лайки поста'),
        ),
    ]
