# Generated by Django 4.1.7 on 2023-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0018_delete_like'),
        ('accounts', '0016_remove_account_laked_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='laked_post',
            field=models.ManyToManyField(related_name='user_likes', to='instagram.post', verbose_name='Лайки поста'),
        ),
    ]
