# Generated by Django 4.1.7 on 2023-04-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_laked_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='laked_post',
        ),
    ]
